### ISSUE TITLE
캐릭터 종류 별 To Do

### ISSUE THREAD

**Issue by az0t0** [SeoulTechTCPGame/HumanSurvival#152]
## 선행 구현 요소
* 캐릭터 선택 화면
* 아래의 캐릭터가 사용하는 무기 총 7종

## 구현
해당 캐릭터의 **구현**: 에셋 적용, 기본 무기 적용, 캐릭터별 스탯 적용, 상점에서 구매와 해금 가능, 플레이 가능

* [ ] 안토니오 벨파에제 구현
* [ ] 이멜다 벨파에제 구현
* [ ] 젠나로 벨파에제 구현
* [ ] 아르카 라돈나 구현
* [ ] 포르타 라돈나 구현
* [ ] 포 랏초 구현
* [ ] 시스터 클레리씨 구현

구현해야할 자세한 내용은 [캐릭터 종류](https://github.com/SUST22Unity/HumanSurvival/wiki/%EC%BA%90%EB%A6%AD%ED%84%B0-%EC%A2%85%EB%A5%98) 문서를 참고하시기 바랍니다.

**Comment by seong0929** [comment]
@rapa1130 , @ryubat , @az0t0 시스터 특수 능력 대체 방안 제시 바랍니다.
