### ISSUE TITLE
무기 - 십자가

### ISSUE THREAD

**Issue by rapa1130** [SeoulTechTCPGame/HumanSurvival#22]
### 십자가
- [x] 레벨 1 수치 입력
- [x] 레벨 별 변화 수치 입력
- [x] 발사 방향 구현
- [x] 반대방향 가속도 적용
- [x] 십자가 이미지 회전 적용
- [ ] 궤적 그래픽 구현

자세한 정보는 [무기 문서 - 십자가 링크](https://github.com/SUST22Unity/HumanSurvival/wiki/Document:-%EB%AC%B4%EA%B8%B0#5-%EC%8B%AD%EC%9E%90%EA%B0%80) 참조

### 천상의 검
- [x] 십자가 재활용
- [x] 진화 조건 적용
- [x] 스킬 기본 수치 적용
- [x] 치명타 적용
- [ ] 그래픽 변화 주기

자세한 내용은 [천상의 검](https://github.com/SUST22Unity/HumanSurvival/wiki/%EC%A7%84%ED%99%94-%EB%AC%B4%EA%B8%B0#5-%EC%A7%84%ED%99%94%EC%B2%9C%EC%83%81%EC%9D%98-%EA%B2%80) 참조

**Comment by seong0929** [comment]
기초 무기를 재활용하지 않고, 사용하지 않는 무기를 진화 무기의 sprite로 활용하였습니다.
![Image](https://github.com/SeoulTechTCPGame/HumanSurvival/assets/50050003/57a782ce-37fb-4f66-a316-163a981d8ed7)
