### ISSUE TITLE
Option 창 세부사항

### ISSUE THREAD

**Issue by az0t0** [SeoulTechTCPGame/HumanSurvival#226]
## 있어야 하는거
* 사운드(=효과음) / 음악: 게임 전체에서 통일되어서 조절 되도록 함
* 시각효과: 광과민성 환자 & 최적화를 위한 옵션으로 각종 이펙트를 줄여줌(밝아지는 효과 위주로)
* 언어 선택
* 피해량 표시: 대미지 표기를 켜고 끔
* 스테이지 진행도 숨기기: 옵션 켜면 게임 소요 시간 표시하지 않음

## 없어도 되는거
* 퍼포먼스 모드
* 클래식 사운드 효과
* 조이스틱 표시

**Comment by seong0929** [comment]
- [사운드 사용처](https://github.com/SUST22Unity/HumanSurvival/discussions/249): 사운드 사용처에 대해 의문이 생겨 디스커션에 질문 남겼습니다

**Comment by rapa1130** [comment]
## 있어야 하는거
* 사운드(=효과음) / 음악: 게임 전체에서 통일되어서 조절 되도록 함
* 창 모드
* 언어 선택


## 없어도 되는거
* 퍼포먼스 모드
* 클래식 사운드 효과
* 조이스틱 표시
* 피해량 표시: 대미지 표기를 켜고 끔
* 스테이지 진행도 숨기기: 옵션 켜면 게임 소요 시간 표시하지 않음
* 시각효과: 광과민성 환자 & 최적화를 위한 옵션으로 각종 이펙트를 줄여줌(밝아지는 효과 위주로)
