### ISSUE TITLE
도우미 아이템

### ISSUE THREAD

**Issue by rapa1130** [SeoulTechTCPGame/HumanSurvival#41]
- [x] 묵주 구현
- [x] 회중 시계 구현
- [x] 흡입기 구현
- [x] 치킨 구현

자세한 내용은 [도우미 아이템 문서 링크](https://github.com/SUST22Unity/HumanSurvival/wiki/%EB%A7%B5-%EC%8A%A4%ED%85%8C%EC%9D%B4%EC%A7%80-%EC%8B%9C%EC%8A%A4%ED%85%9C#%EB%8F%84%EC%9A%B0%EB%AF%B8-%EC%95%84%EC%9D%B4%ED%85%9C) 참조

**Comment by seong0929** [comment]
- 오성혁: 묵주 구현
- 유혁진: 흡입기 구현

**Comment by seong0929** [comment]
회중 시계: 오성혁, 박지훈
