### ISSUE TITLE
개발 중 태그 통일을 위한 논의

### ISSUE THREAD

**Issue by seong0929** [SeoulTechTCPGame/HumanSurvival#42]
여러 명이 동시에 개발하므로 태그에 대한 통일이 필요하다는 생각에 태그를 정리하기 위해 이슈를 만들었습니다. 새로 태그를 만들었으면 태그에 대한 설명과 함께 이 곳에 정리해주세요.

현재 태그
(기본 태그)
Untagged
Respawn
Finish
EditorOnly
MainCamera
(누군가 만든 태그)
Player
GameController

**Comment by seong0929** [comment]
Monster - 몬스터 확인을 위한 태그

**Comment by Jeon-YJ1004** [comment]
--Enemies--  :  몬스터 생성을 위한 태그

**Comment by yhj0329** [comment]
Weapon - 무기 확인을 위한 태그

**Comment by seong0929** [comment]
Ground - 타일의 범위를 나타내기 위한 태그
Area - 타일이 벗어났는지 확인하기 위한 태그

**Comment by seong0929** [comment]
Object - 오브젝트 확인 충돌 감지를 위한 태그

**Comment by Jeon-YJ1004** [comment]
HealItem - drop 아이템 중 힐을 하는 오브젝트 태그
ExpItem - drop 아이템 중 경험치 추가를 하는 오브젝트 태그

**Comment by seong0929** [comment]
Boundary - 무기가 화면 밖을 나갈 때 삭제되거나 튕기는 영역을 확인하기 위한 태그

**Comment by pianoop** [comment]
WeaponSub - 특이한 무기들을 보조해주는 오브젝트 태그 (비둘기, 원 같은 것)

**Comment by pianoop** [comment]
HealObj, ExpObj, CoinObj 삭제 후 CollectibleObj로 통합
